from pathlib import Path
p = Path('/home/ubuntu/football-intelligence/client/src/pages/Home.tsx')
s = p.read_text()
s = s.replace('''  const [submitted, setSubmitted] = useState(false);\n  const [form, setForm] = useState({ name: "", contact: "", source: getAcquisitionSource() });''', '''  const [submitted, setSubmitted] = useState(false);\n  const [serverState, setServerState] = useState<{ prospectId: string; payment?: string; telegram?: string }>({ prospectId: "" });\n  const [form, setForm] = useState({ name: "", contact: "", source: getAcquisitionSource() });''')
old = '''<p className="mt-2 text-sm leading-6 text-[#9fb0a5]">Your signup is captured with cohort {variant} at {formatNaira(variant)}. Payment and Telegram activation remain the next integration steps; no payment has been processed in this static validation build.</p><div className="mt-5 rounded-lg border border-[#f3c978]/20 bg-[#f3c978]/[.05] p-4 text-[12px] leading-5 text-[#cdbf9f]">Owner action required: connect a reviewed payment provider, then record payment reference, payment status, amount and purchase timestamp before enabling live checkout.</div>'''
new = '''<p className="mt-2 text-sm leading-6 text-[#9fb0a5]">Signup and checkout initiation are now recorded by the non-live server in cohort {variant} at {formatNaira(variant)}. No real payment has been processed.</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><button onClick={async () => { const result = await fetch("/api/validation/mock/payment", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prospect_id: serverState.prospectId, success: true }) }).then((response) => response.json()); setServerState((state) => ({ ...state, payment: result.payment_status })); track("payment_completed", { prospect_id: serverState.prospectId, payment_reference: result.payment_reference, payment_amount: result.payment_amount, pricing_variant: variant, acquisition_source: form.source, mock: "true" }); }} className="btn btn-primary !text-[12px]">Simulate payment success</button><button onClick={async () => { const result = await fetch("/api/validation/mock/telegram", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prospect_id: serverState.prospectId, telegram_identifier: form.contact }) }).then((response) => response.json()); setServerState((state) => ({ ...state, telegram: result.activation_status })); track("telegram_activated", { prospect_id: serverState.prospectId, mock: "true" }); }} className="btn btn-ghost !text-[12px]">Simulate Telegram activation</button></div><p className="mt-4 text-[11px] leading-5 text-[#9fb0a5]">Server status: payment {serverState.payment ?? "pending"} · Telegram {serverState.telegram ?? "pending"}. These are development/mock actions only.</p><div className="mt-5 rounded-lg border border-[#f3c978]/20 bg-[#f3c978]/[.05] p-4 text-[12px] leading-5 text-[#cdbf9f]">Owner action required: connect a reviewed payment provider and Telegram bot before enabling live checkout or activation.</div>'''
if old not in s: raise SystemExit('submitted block not found')
s = s.replace(old, new)
old_submit = '''const prospectId = window.localStorage.getItem("fi_prospect_id") ?? `prospect-${Date.now()}`; window.localStorage.setItem("fi_prospect_id", prospectId); window.localStorage.setItem("fi_signup", JSON.stringify({ prospect_id: prospectId, name: form.name, contact: form.contact, acquisition_source: form.source, pricing_variant: variant, assigned_price: formatNaira(variant), assigned_at: window.localStorage.getItem("fi_pricing_assigned_at") ?? new Date().toISOString(), payment_status: "pending", payment_amount: formatNaira(variant), payment_reference: "", purchased_at: "" })); track("checkout_started", { prospect_id: prospectId, pricing_variant: variant, assigned_price: formatNaira(variant), acquisition_source: form.source }); setSubmitted(true);'''
new_submit = '''const created = await fetch("/api/validation/prospects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.name, phone_or_telegram: form.contact, acquisition_source: form.source }) }).then((response) => response.json()); const checkout = await fetch("/api/validation/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prospect_id: created.prospect.id }) }).then((response) => response.json()); window.localStorage.setItem("fi_prospect_id", created.prospect.id); window.localStorage.setItem("fi_signup", JSON.stringify({ prospect_id: created.prospect.id, acquisition_source: created.prospect.acquisition_source, pricing_variant: created.assignment.variant, assigned_price: created.assignment.assigned_price, checkout_amount: checkout.amount, payment_status: "pending" })); setServerState({ prospectId: created.prospect.id }); track("checkout_started", { prospect_id: created.prospect.id, pricing_variant: created.assignment.variant, assigned_price: created.assignment.assigned_price, acquisition_source: created.prospect.acquisition_source }); setSubmitted(true);'''
if old_submit not in s: raise SystemExit('submit block not found')
s = s.replace(old_submit, new_submit)
p.write_text(s)
print('bridged trial form to non-live server APIs')
